[tool.black]
line_length = 99
target_version = ["py312"]

[tool.isort]
line_length = 99
profile = "black"
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
